name: Trivy

on:
  push:
  pull_request:

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the source code
      - uses: actions/checkout@v4
        name: Checkout source code

      # Cache Trivy database to speed up subsequent runs
      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: ${{ runner.os }}-trivy-db
          restore-keys: |
            ${{ runner.os }}-trivy-db

      # Run Trivy scan
      - name: Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          hide-progress: true
          exit-code: "0" # Set to 0 to avoid failing the workflow
          ignore-unfixed: true # Skip vulnerabilities without fixes
          severity: "HIGH,CRITICAL" # Only show high and critical vulnerabilities
